JS-0417
KayleAI/kayle pull request #14
Opened 2024-09-09 11:14 UTC by wanapichpongsa

Changes on 8th of Sep, 2024 have been overridden so please ignore.

I used React.useCallback for all the issues Deepsource flagged. Latest commit was line fix from autoci

2024-09-09 12:23 UTC, wanapichpongsa commented
JS-0045 has also been attended to

2024-09-17 07:36 UTC, wanapichpongsa commented on platform/components/docs/Search.tsx
@arsenstorm can you please let me know if there are any more introduced occurences?

2024-09-17 08:07 UTC, arsenstorm requested changes
Good so far, but some changes are needed for performance and safety.

2024-09-17 08:07 UTC, arsenstorm commented on platform/actions/keys/create-api-key.ts
Use an if statement to check if the environment variables are set, otherwise throw an error.

2024-09-17 08:07 UTC, arsenstorm commented on platform/actions/keys/delete-api-key.ts
Use an if statement to check if the environment variables are set, otherwise throw an error.

2024-09-17 08:07 UTC, arsenstorm commented on platform/actions/keys/get-api-usage.ts
Use an if statement to check if the environment variables are set, otherwise throw an error.

2024-09-17 08:07 UTC, arsenstorm commented on platform/actions/keys/list-all-keys.ts
Use an if statement to check if the environment variables are set, otherwise throw an error.

2024-09-17 08:07 UTC, arsenstorm commented on platform/actions/keys/update-api-key.ts
Use an if statement to check if the environment variables are set, otherwise throw an error.

2024-09-17 08:07 UTC, arsenstorm commented on platform/app/api/demo/route.ts
Use an if statement to check if the environment variables are set, otherwise throw an error.

2024-09-17 08:07 UTC, arsenstorm commented on platform/app/api/hunt/route.ts
Use an if statement to check if the environment variables are set, otherwise throw an error.

2024-09-17 08:07 UTC, arsenstorm commented on platform/app/providers.tsx
Use an if statement to check if the environment variables are set, otherwise return null - Analytics are optional.

2024-09-17 08:07 UTC, arsenstorm commented on platform/components/docs/GenerateSEO.tsx
Use `??` instead of `||`

2024-09-17 08:07 UTC, arsenstorm commented on platform/components/docs/Search.tsx
If `SearchDialogContent` is unused, then there is still at least one problem.

2024-09-17 08:07 UTC, arsenstorm commented on platform/middleware.ts
Use an if statement to check if the environment variables are set, otherwise throw an error.

2024-09-17 09:07 UTC, wanapichpongsa commented on platform/components/docs/GenerateSEO.tsx
Since `"kayle.ai"` is non-null, shouldn't we use `||`?

2024-09-17 09:34 UTC, arsenstorm commented on platform/components/docs/GenerateSEO.tsx
No. `kayle.ai` is the fallback if `process.env.VERCEL_PROJECT_PRODUCTION_URL` is `null` or `undefined`. We *could* use `||` instead, but I prefer the `??` operator since it only checks for `null` or `undefined` and not `0`, `false`, or ` `.

2024-09-19 19:13 UTC, arsenstorm requested changes

2024-09-19 19:13 UTC, arsenstorm commented on packages/database/src/server.ts
This is **not** fixed. An error will **never** be thrown because `supabaseUrl` and `supabaseAnonKey` are **always** defined.

2024-09-19 19:13 UTC, arsenstorm commented on platform/actions/keys/create-api-key.ts
This is not fixed. An error will never be thrown because `rootKey` is always defined.

2024-09-19 19:13 UTC, arsenstorm commented on platform/actions/keys/get-api-key.ts
This is not fixed. An error will never be thrown because `rootKey` is always defined.

2024-09-19 19:13 UTC, arsenstorm commented on platform/actions/keys/get-api-usage.ts
This is not fixed. An error will never be thrown because `rootKey` is always defined.

2024-09-19 19:13 UTC, arsenstorm commented on platform/actions/keys/list-all-keys.ts
This is not fixed. An error will never be thrown because `rootKey` is always defined.

2024-09-19 19:13 UTC, arsenstorm commented on platform/actions/keys/update-api-key.ts
This is not fixed. An error will never be thrown because `rootKey` is always defined.

2024-09-19 19:13 UTC, arsenstorm commented on platform/app/api/demo/route.ts
This is not fixed. An error will never be thrown because `ajKey` is always defined.

2024-09-19 19:13 UTC, arsenstorm commented on platform/app/api/hunt/route.ts
This is not fixed. An error will never be thrown because `KAYLE_API_KEY` is always defined.

2024-09-19 19:13 UTC, arsenstorm commented on platform/app/providers.tsx
This is not fixed. An error will never be thrown because `clientId` is always defined.

2024-09-19 19:13 UTC, arsenstorm commented on platform/components/docs/Search.tsx
What's changed here?

2024-09-19 19:13 UTC, arsenstorm commented on platform/middleware.ts
This is not fixed. An error will never be thrown because `supabaseUrl` and `supabaseAnonKey` are always defined.

2024-10-14 19:48 UTC, arsenstorm approved these changes
LGTM

2024-10-14 19:49 UTC, merged